name: google_map_animation
description: "A Flutter library for creating animated polylines and markers on Google Maps with smooth transitions and customizable effects."


version: 0.1.0

repository: https://github.com/manishrelani/google_map_animation
issue_tracker: https://github.com/manishrelani/google_map_animation/issues

environment:
  sdk: ^3.8.1
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter_platform_interface: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

# Add topics for better discoverability
topics:
  - map-animation
  - animated-markers
  - animated-polylines
  - animated-bearings




















